// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGoQYEuF7i9WWX0LrFHRrPf-Hp3FYtEps',
    appId: '1:754417275926:android:95f27ca74819851d09d137',
    messagingSenderId: '754417275926',
    projectId: 'todofirebase-f3f30',
    databaseURL: 'https://todofirebase-f3f30-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'todofirebase-f3f30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeOsOu8GhSXAmuMfT__hB4XLAUqX6YhqY',
    appId: '1:754417275926:ios:55fe2a1d2fe1b0af09d137',
    messagingSenderId: '754417275926',
    projectId: 'todofirebase-f3f30',
    databaseURL: 'https://todofirebase-f3f30-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'todofirebase-f3f30.appspot.com',
    androidClientId: '754417275926-uo49a994ut8qpj0sk1b1bj0ar3vvru6g.apps.googleusercontent.com',
    iosBundleId: 'com.debi.coursely',
  );
}
